/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_biquadfilter_free: (a: number, b: number) => void;
export const biquadfilter_new: () => number;
export const biquadfilter_process: (a: number, b: number) => number;
export const biquadfilter_set_coefficients: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const biquadfilter_reset: (a: number) => void;
export const __wbg_threebandeq_free: (a: number, b: number) => void;
export const threebandeq_new: (a: number) => number;
export const threebandeq_update_coefficients: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const threebandeq_process: (a: number, b: number) => number;
export const threebandeq_reset: (a: number) => void;
export const __wbg_wasmaudioprocessor_free: (a: number, b: number) => void;
export const wasmaudioprocessor_new: (a: number) => number;
export const wasmaudioprocessor_process_buffer: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: any, i: number, j: number, k: any, l: number, m: number, n: number, o: number, p: number, q: number, r: number) => void;
export const wasmaudioprocessor_update_eq_coefficients: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasmaudioprocessor_reset: (a: number) => void;
export const __wbg_unifiedmixerprocessor_free: (a: number, b: number) => void;
export const unifiedmixerprocessor_new: (a: number, b: number) => number;
export const unifiedmixerprocessor_process_mix: (a: number, b: number, c: number, d: number, e: number, f: any, g: number, h: number, i: any, j: number, k: number) => void;
export const unifiedmixerprocessor_set_channel_params: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const unifiedmixerprocessor_set_channel_eq: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const unifiedmixerprocessor_set_channel_compression: (a: number, b: number, c: number, d: number) => void;
export const unifiedmixerprocessor_reset: (a: number) => void;
export const unifiedmixerprocessor_get_num_channels: (a: number) => number;
export const __wbg_reverbprocessor_free: (a: number, b: number) => void;
export const reverbprocessor_new: (a: number) => number;
export const reverbprocessor_process: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: any, i: number, j: number, k: any, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number) => void;
export const reverbprocessor_reset: (a: number) => void;
export const __wbindgen_export_0: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_start: () => void;
